import { defineInfoschematic } from '@infoschematics/domain-core'

const packagePorts = {
  east: 2,
  north: 6,
  south: 6,
  west: 2,
} as const

const packageCard = (
  code: string,
  id: string,
  label: string,
  detail: string,
  scope: string,
  domain: string,
  stereotype: string,
  x: number,
  y: number,
  width = 280,
) => ({
  code,
  detail,
  domain,
  id,
  label,
  placement: {
    box: { height: 90, width, x, y },
    ports: packagePorts,
  },
  scope,
  scopes: [scope],
  stereotype,
})

const dependency = (
  code: string,
  id: string,
  source: string,
  sourcePort: `N${number}` | `E${number}` | `S${number}` | `W${number}`,
  target: string,
  targetPort: `N${number}` | `E${number}` | `S${number}` | `W${number}`,
  points: readonly { x: number; y: number }[],
) => ({
  code,
  family: 'dependency',
  id,
  points,
  source,
  sourcePort,
  target,
  targetPort,
})

export const infoschematicsInfoschematic = defineInfoschematic({
  id: 'infoschematics-architecture',
  title: 'An Infoschematic of Infoschematics',
  subtitle: 'One serialisable product from authored data to public host',
  synopsis:
    'The repository separates its authored contract, framework-neutral behaviour, interactive Views, renderers, examples, and hosts with dependencies pointing toward lower-level packages.',
  takeaways: [
    'Domain Model is the dependency root.',
    'Interactive Views add capability without reversing package ownership.',
    'Examples contain authored data; hosts choose how to present it.',
  ],
  infoschematic: {
    viewBox: { height: 920, width: 1400, x: 0, y: 0 },
    appearance: {
      surface: 'blueprint',
      grid: 'major-plus-minor',
      card: {
        compact: true,
        identity: true,
        stereotype: true,
        description: false,
      },
    },
    domains: [
      {
        color: '#2456a6',
        description: 'Reusable contracts and framework-neutral behaviour.',
        fill: '#e8f0ff',
        id: 'product-foundation',
        label: 'Product foundation',
      },
      {
        color: '#087f5b',
        description: 'Interactive capability for Producers and Audiences.',
        fill: '#e4f7ef',
        id: 'interactive-experience',
        label: 'Interactive experience',
      },
      {
        color: '#a23b72',
        description: 'Authored and rendered outlets for sharing Infoschematics.',
        fill: '#fdebf5',
        id: 'publication',
        label: 'Publication',
      },
    ],
    scopes: [
      {
        color: '#2456a6',
        description: 'Dependency-free authored product types.',
        fill: '#e8f0ff',
        id: 'domain-contract',
        label: 'Domain contract',
        prefix: 'DM',
      },
      {
        color: '#5b4aa8',
        description: 'Framework-neutral domain and visual calculations.',
        fill: '#f0edff',
        id: 'neutral-behaviour',
        label: 'Framework-neutral behaviour',
        prefix: 'FN',
      },
      {
        color: '#087f5b',
        description: 'Additive interactive Views.',
        fill: '#e4f7ef',
        id: 'interactive-views',
        label: 'Interactive Views',
        prefix: 'VW',
      },
      {
        color: '#9a6700',
        description: 'Framework-neutral rendering output.',
        fill: '#fff4d6',
        id: 'renderer-output',
        label: 'Renderer output',
        prefix: 'RO',
      },
      {
        color: '#a23b72',
        description: 'Independently authored Infoschematic definitions.',
        fill: '#fdebf5',
        id: 'authored-examples',
        label: 'Authored examples',
        prefix: 'EX',
      },
      {
        color: '#b54708',
        description: 'Deployable composition and publication hosts.',
        fill: '#fff0e5',
        id: 'application-hosts',
        label: 'Application hosts',
        prefix: 'HOST',
      },
    ],
    flowFamilies: [
      {
        color: '#52606d',
        description: 'A package or host consumes a lower-level package.',
        id: 'dependency',
        label: 'Depends on',
        prefix: 'DEP',
      },
    ],
    lanes: [
      {
        appearance: { frame: 'notched', label: 'north-west' },
        height: 160,
        id: 'lane-domain-contract',
        label: 'Authored contract',
        labelY: 48,
        panel: { height: 160, radius: 12, width: 1360, x: 20, y: 20 },
        y: 20,
        zones: [
          {
            appearance: { frame: 'plain', label: 'south-east' },
            fill: '#e8f0ff',
            id: 'zone-domain-model',
            label: 'Dependency root',
            width: 1360,
            x: 20,
          },
        ],
      },
      {
        appearance: { frame: 'notched', label: 'north' },
        height: 170,
        id: 'lane-neutral-behaviour',
        label: 'Framework-neutral behaviour',
        labelY: 238,
        panel: { height: 170, radius: 12, width: 1360, x: 20, y: 210 },
        y: 210,
        zones: [
          {
            appearance: { frame: 'plain', label: 'west' },
            fill: '#f4f0ff',
            id: 'zone-domain-behaviour',
            label: 'Domain behaviour',
            width: 680,
            x: 20,
          },
          {
            appearance: { frame: 'plain', label: 'east' },
            fill: '#ece9ff',
            id: 'zone-view-calculations',
            label: 'View calculations',
            width: 680,
            x: 700,
          },
        ],
      },
      {
        appearance: { frame: 'notched', label: 'north-east' },
        height: 170,
        id: 'lane-output-packages',
        label: 'View and renderer packages',
        labelY: 438,
        panel: { height: 170, radius: 12, width: 1360, x: 20, y: 410 },
        y: 410,
        zones: [
          {
            appearance: { frame: 'plain', label: 'south-west' },
            fill: '#e4f7ef',
            id: 'zone-interactive-views',
            label: 'Additive interactive Views',
            width: 1000,
            x: 20,
          },
          {
            appearance: { frame: 'plain', label: 'south-east' },
            fill: '#fff4d6',
            id: 'zone-static-output',
            label: 'Static output',
            width: 360,
            x: 1020,
          },
        ],
      },
      {
        appearance: { frame: 'notched', label: 'south' },
        height: 230,
        id: 'lane-composition',
        label: 'Authored composition',
        labelY: 688,
        panel: { height: 230, radius: 12, width: 1360, x: 20, y: 660 },
        y: 660,
        zones: [
          {
            appearance: { frame: 'plain', label: 'north-west' },
            fill: '#fdebf5',
            id: 'zone-authored-examples',
            label: 'Authored examples',
            width: 680,
            x: 20,
          },
          {
            appearance: { frame: 'plain', label: 'north-east' },
            fill: '#fff0e5',
            id: 'zone-application-hosts',
            label: 'Application hosts',
            width: 680,
            x: 700,
          },
        ],
      },
    ],
    cards: [
      packageCard(
        'PKG-DM',
        'package-domain-model',
        'Domain Model',
        'Serialisable authored product types and no package dependencies.',
        'domain-contract',
        'product-foundation',
        'package',
        560,
        65,
        280,
      ),
      packageCard(
        'PKG-DC',
        'package-domain-core',
        'Domain Core',
        'Framework-neutral defaults and domain behaviour.',
        'neutral-behaviour',
        'product-foundation',
        'package',
        180,
        255,
        280,
      ),
      packageCard(
        'PKG-VM',
        'package-view-model',
        'View Model',
        'Framework-neutral geometry, routing, presentation, and editing calculations.',
        'neutral-behaviour',
        'product-foundation',
        'package',
        900,
        255,
        280,
      ),
      packageCard(
        'PKG-VC',
        'package-view-canvas',
        'Canvas View',
        'Reusable interactive Infoschematic surface.',
        'interactive-views',
        'interactive-experience',
        'package',
        80,
        450,
      ),
      packageCard(
        'PKG-VP',
        'package-view-present',
        'Present View',
        'Audience focus, navigation, Callouts, and Story playback over Canvas.',
        'interactive-views',
        'interactive-experience',
        'package',
        380,
        450,
      ),
      packageCard(
        'PKG-VS',
        'package-view-studio',
        'Studio View',
        'Producer-facing Design and Direct capability over Present.',
        'interactive-views',
        'interactive-experience',
        'package',
        680,
        450,
      ),
      packageCard(
        'PKG-SVG',
        'package-render-svg',
        'SVG Renderer',
        'Deterministic static SVG from the same authored definition.',
        'renderer-output',
        'publication',
        'package',
        1080,
        450,
      ),
      packageCard(
        'EX-IS',
        'example-infoschematics',
        'Authored examples',
        'Independent serialisable products depending only on Domain Core.',
        'authored-examples',
        'publication',
        'Infoschematic',
        220,
        710,
        280,
      ),
      packageCard(
        'HOST-SITE',
        'host-site',
        'Public Site',
        'Host-owned routing, metadata, composition, and deployment.',
        'application-hosts',
        'publication',
        'application',
        900,
        710,
        280,
      ),
    ],
    flows: [
      dependency('DEP-001', 'dependency-domain-core-domain-model', 'package-domain-core', 'N1', 'package-domain-model', 'S1', [
        { x: 220, y: 255 },
        { x: 220, y: 200 },
        { x: 600, y: 200 },
        { x: 600, y: 155 },
      ]),
      dependency('DEP-002', 'dependency-view-model-domain-model', 'package-view-model', 'N1', 'package-domain-model', 'S2', [
        { x: 940, y: 255 },
        { x: 940, y: 190 },
        { x: 640, y: 190 },
        { x: 640, y: 155 },
      ]),
      dependency('DEP-003', 'dependency-canvas-domain-model', 'package-view-canvas', 'N1', 'package-domain-model', 'S3', [
        { x: 120, y: 450 },
        { x: 120, y: 400 },
        { x: 680, y: 400 },
        { x: 680, y: 155 },
      ]),
      dependency('DEP-004', 'dependency-canvas-view-model', 'package-view-canvas', 'N2', 'package-view-model', 'S1', [
        { x: 160, y: 450 },
        { x: 160, y: 390 },
        { x: 940, y: 390 },
        { x: 940, y: 345 },
      ]),
      dependency('DEP-005', 'dependency-present-domain-model', 'package-view-present', 'N1', 'package-domain-model', 'S4', [
        { x: 420, y: 450 },
        { x: 420, y: 380 },
        { x: 720, y: 380 },
        { x: 720, y: 155 },
      ]),
      dependency('DEP-006', 'dependency-present-view-model', 'package-view-present', 'N2', 'package-view-model', 'S2', [
        { x: 460, y: 450 },
        { x: 460, y: 370 },
        { x: 980, y: 370 },
        { x: 980, y: 345 },
      ]),
      dependency('DEP-007', 'dependency-present-canvas', 'package-view-present', 'W1', 'package-view-canvas', 'E1', [
        { x: 380, y: 480 },
      { x: 360, y: 480 },
      ]),
      dependency('DEP-008', 'dependency-studio-domain-core', 'package-view-studio', 'N1', 'package-domain-core', 'S1', [
        { x: 720, y: 450 },
        { x: 720, y: 360 },
        { x: 220, y: 360 },
        { x: 220, y: 345 },
      ]),
      dependency('DEP-009', 'dependency-studio-domain-model', 'package-view-studio', 'N2', 'package-domain-model', 'S5', [
        { x: 760, y: 450 },
        { x: 760, y: 155 },
      ]),
      dependency('DEP-010', 'dependency-studio-view-model', 'package-view-studio', 'N3', 'package-view-model', 'S3', [
        { x: 800, y: 450 },
        { x: 800, y: 350 },
        { x: 1020, y: 350 },
        { x: 1020, y: 345 },
      ]),
      dependency('DEP-011', 'dependency-studio-canvas', 'package-view-studio', 'W2', 'package-view-canvas', 'E2', [
        { x: 680, y: 510 },
      { x: 360, y: 510 },
      ]),
      dependency('DEP-012', 'dependency-studio-present', 'package-view-studio', 'W1', 'package-view-present', 'E1', [
        { x: 680, y: 480 },
      { x: 660, y: 480 },
      ]),
      dependency('DEP-013', 'dependency-render-svg-domain-model', 'package-render-svg', 'N1', 'package-domain-model', 'S6', [
        { x: 1120, y: 450 },
        { x: 1120, y: 360 },
        { x: 800, y: 360 },
        { x: 800, y: 155 },
      ]),
      dependency('DEP-014', 'dependency-render-svg-view-model', 'package-render-svg', 'N2', 'package-view-model', 'S4', [
        { x: 1160, y: 450 },
        { x: 1160, y: 350 },
        { x: 1060, y: 350 },
        { x: 1060, y: 345 },
      ]),
      dependency('DEP-015', 'dependency-example-domain-core', 'example-infoschematics', 'N1', 'package-domain-core', 'S2', [
        { x: 260, y: 710 },
        { x: 260, y: 345 },
      ]),
      dependency('DEP-016', 'dependency-site-studio', 'host-site', 'N1', 'package-view-studio', 'S1', [
        { x: 940, y: 710 },
        { x: 940, y: 630 },
        { x: 720, y: 630 },
        { x: 720, y: 540 },
      ]),
      dependency('DEP-017', 'dependency-site-example', 'host-site', 'W1', 'example-infoschematics', 'E1', [
        { x: 900, y: 740 },
        { x: 500, y: 740 },
      ]),
    ],
  },
  standaloneScenes: [
    {
      code: 'SCN-01',
      description: 'The dependency-free contract supports two independent framework-neutral behaviour packages.',
      focus: {
        artefacts: ['package-domain-model', 'package-domain-core', 'package-view-model'],
        flows: ['dependency-domain-core-domain-model', 'dependency-view-model-domain-model'],
      },
      id: 'scene-foundations',
      label: 'Start with the foundations',
      short: 'Domain Model is the dependency root.',
    },
    {
      code: 'SCN-02',
      description: 'Canvas, Present, and Studio add interactive capability in one direction while retaining the lower-level contracts.',
      focus: {
        artefacts: [
          'package-domain-model',
          'package-view-model',
          'package-view-canvas',
          'package-view-present',
          'package-view-studio',
        ],
        flows: [
          'dependency-canvas-domain-model',
          'dependency-canvas-view-model',
          'dependency-present-domain-model',
          'dependency-present-view-model',
          'dependency-present-canvas',
          'dependency-studio-domain-model',
          'dependency-studio-view-model',
          'dependency-studio-canvas',
          'dependency-studio-present',
        ],
      },
      id: 'scene-additive-views',
      label: 'Add interactive Views',
      short: 'Each View builds on narrower capability.',
    },
    {
      code: 'SCN-03',
      description: 'Static rendering stays framework-neutral, authored examples contain only product data, and the Site owns publication.',
      focus: {
        artefacts: [
          'package-domain-core',
          'package-domain-model',
          'package-view-model',
          'package-view-studio',
          'package-render-svg',
          'example-infoschematics',
          'host-site',
        ],
        flows: [
          'dependency-render-svg-domain-model',
          'dependency-render-svg-view-model',
          'dependency-example-domain-core',
          'dependency-site-studio',
          'dependency-site-example',
        ],
      },
      id: 'scene-public-outlets',
      label: 'Compose examples and hosts',
      short: 'Authored data remains separate from its outlets.',
    },
    {
      code: 'SCN-04',
      description: 'The complete product graph keeps dependencies pointing toward lower-level packages.',
      focus: {
        artefacts: [
          'package-domain-model',
          'package-domain-core',
          'package-view-model',
          'package-view-canvas',
          'package-view-present',
          'package-view-studio',
          'package-render-svg',
          'example-infoschematics',
          'host-site',
        ],
        flows: [
          'dependency-domain-core-domain-model',
          'dependency-view-model-domain-model',
          'dependency-canvas-domain-model',
          'dependency-canvas-view-model',
          'dependency-present-domain-model',
          'dependency-present-view-model',
          'dependency-present-canvas',
          'dependency-studio-domain-core',
          'dependency-studio-domain-model',
          'dependency-studio-view-model',
          'dependency-studio-canvas',
          'dependency-studio-present',
          'dependency-render-svg-domain-model',
          'dependency-render-svg-view-model',
          'dependency-example-domain-core',
          'dependency-site-studio',
          'dependency-site-example',
        ],
      },
      id: 'scene-complete-architecture',
      label: 'See the complete architecture',
      short: 'One-way dependencies keep ownership clear.',
    },
  ],
  stories: [
    {
      code: 'STORY-01',
      id: 'story-from-contract-to-host',
      question: 'How does one authored Infoschematic reach its Audience?',
      scenes: [
        {
          anchor: 'package-domain-model',
          callout: {
            body: 'Begin with serialisable product data and a dependency-free contract.',
            takeaways: ['The Domain Model imports no package.'],
          },
          duration: 5,
          id: 'story-scene-foundations',
          sourceScene: 'scene-foundations',
          title: 'Define the product',
        },
        {
          anchor: 'package-view-studio',
          callout: {
            body: 'Add Canvas, Present, and Studio capability without moving authored state into a View.',
            takeaways: ['Views depend downward; authored products do not depend on Views.'],
          },
          duration: 6,
          id: 'story-scene-views',
          sourceScene: 'scene-additive-views',
          title: 'Choose the narrowest View',
        },
        {
          anchor: 'host-site',
          callout: {
            body: 'Let examples own reusable data and let the Site own routing, metadata, and deployment.',
            takeaways: ['The same definition can drive Studio and deterministic SVG.'],
          },
          duration: 6,
          id: 'story-scene-outlets',
          sourceScene: 'scene-public-outlets',
          title: 'Publish through a host',
        },
      ],
      short: 'From serialisable contract to public outlet.',
      title: 'From contract to Audience',
    },
  ],
  calloutPositions: [
    { x: 70, y: 95 },
    { x: 1010, y: 235 },
    { x: 1040, y: 680 },
  ],
})

export const infoschematicsExample = infoschematicsInfoschematic
