import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'

import {
  visualTokens,
  type VisualTokenValue,
} from '../packages/view-model/src/tokens.ts'

export type VisualTokenEntry = Readonly<{
  cssName: `--infoschematic-${string}`
  path: string
  value: VisualTokenValue
}>

export interface TokenTree {
  readonly [key: string]: TokenTree | VisualTokenValue
}

const cssSegment = (segment: string) =>
  segment
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()

/** Flatten and validate a token tree in deterministic CSS-name order. */
export const visualTokenEntries = (
  tokens: TokenTree = visualTokens,
): readonly VisualTokenEntry[] => {
  const entries: VisualTokenEntry[] = []

  const visit = (tree: TokenTree, parent: readonly string[]) => {
    for (const [key, value] of Object.entries(tree)) {
      const path = [...parent, key]
      if (typeof value === 'object' && value !== null) {
        visit(value, path)
        continue
      }

      const segments = path.map(cssSegment)
      if (segments.some((segment) => segment.length === 0)) {
        throw new Error(
          `Visual token path cannot produce an empty CSS segment: ${path.join('.')}`,
        )
      }

      entries.push({
        cssName: `--infoschematic-${segments.join('-')}`,
        path: path.join('.'),
        value,
      })
    }
  }

  visit(tokens, [])
  entries.sort((left, right) =>
    left.cssName < right.cssName ? -1 : left.cssName > right.cssName ? 1 : 0,
  )

  const pathsByName = new Map<string, string>()
  for (const entry of entries) {
    const firstPath = pathsByName.get(entry.cssName)
    if (firstPath) {
      throw new Error(
        `Visual token CSS name collision for ${entry.cssName}: ${firstPath}, ${entry.path}`,
      )
    }
    pathsByName.set(entry.cssName, entry.path)
  }

  return Object.freeze(entries.map((entry) => Object.freeze(entry)))
}

export const generateVisualTokenCss = (
  tokens: TokenTree = visualTokens,
): string => {
  const declarations = visualTokenEntries(tokens).map(
    (entry) => `  ${entry.cssName}: ${String(entry.value)};`,
  )

  return [
    '/* Generated by scripts/generate-visual-tokens.ts. Do not edit. */',
    ':root {',
    ...declarations,
    '}',
    '',
  ].join('\n')
}

export const generatedVisualTokensUrl = new URL(
  '../packages/view-model/src/tokens.generated.css',
  import.meta.url,
)

export const generateVisualTokens = async ({
  check = false,
  output = generatedVisualTokensUrl,
}: {
  check?: boolean
  output?: URL
} = {}): Promise<void> => {
  const expected = generateVisualTokenCss()

  if (check) {
    const actual = await readFile(output, 'utf8').catch(() => undefined)
    if (actual !== expected) {
      throw new Error(
        `Generated visual tokens are stale: ${fileURLToPath(output)}. Run bun scripts/generate-visual-tokens.ts.`,
      )
    }
    return
  }

  await writeFile(output, expected)
}

const invokedPath = process.argv[1]
  ? pathToFileURL(process.argv[1]).href
  : undefined
if (invokedPath === import.meta.url) {
  generateVisualTokens({
    check: process.argv.slice(2).includes('--check'),
  }).catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error)
    process.exitCode = 1
  })
}
