#!/usr/bin/env bun
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { type VisualTokenValue, visualTokens } from '../packages/view-model/src/tokens.ts'
import { type CliSpec, isDirectInvocation, runCli } from './cli.ts'

export type VisualTokenEntry = Readonly<{
  cssName: `--infoschematic-${string}`
  path: string
  value: VisualTokenValue
}>

export interface TokenTree {
  readonly [key: string]: TokenTree | VisualTokenValue
}

const cssSegment = (segment: string) =>
  segment
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()

/** Flatten and validate a token tree in deterministic CSS-name order. */
export const visualTokenEntries = (tokens: TokenTree = visualTokens): readonly VisualTokenEntry[] => {
  const entries: VisualTokenEntry[] = []

  const visit = (tree: TokenTree, parent: readonly string[]) => {
    for (const [key, value] of Object.entries(tree)) {
      const path = [...parent, key]
      if (typeof value === 'object' && value !== null) {
        visit(value, path)
        continue
      }

      const segments = path.map(cssSegment)
      if (segments.some((segment) => segment.length === 0)) {
        throw new Error(`Visual token path cannot produce an empty CSS segment: ${path.join('.')}`)
      }

      entries.push({
        cssName: `--infoschematic-${segments.join('-')}`,
        path: path.join('.'),
        value
      })
    }
  }

  visit(tokens, [])
  entries.sort((left, right) => (left.cssName < right.cssName ? -1 : left.cssName > right.cssName ? 1 : 0))

  const pathsByName = new Map<string, string>()
  for (const entry of entries) {
    const firstPath = pathsByName.get(entry.cssName)
    if (firstPath) {
      throw new Error(`Visual token CSS name collision for ${entry.cssName}: ${firstPath}, ${entry.path}`)
    }
    pathsByName.set(entry.cssName, entry.path)
  }

  return Object.freeze(entries.map((entry) => Object.freeze(entry)))
}

export const generateVisualTokenCss = (tokens: TokenTree = visualTokens): string => {
  const declarations = visualTokenEntries(tokens).map((entry) => `  ${entry.cssName}: ${String(entry.value)};`)

  return [
    '/* Generated by scripts/generate-visual-tokens.ts. Do not edit. */',
    ':root {',
    ...declarations,
    '}',
    ''
  ].join('\n')
}

export const generatedVisualTokensUrl = new URL('../packages/view-model/src/tokens.generated.css', import.meta.url)

export const generateVisualTokens = async ({
  check = false,
  output = generatedVisualTokensUrl
}: {
  check?: boolean
  output?: URL
} = {}): Promise<void> => {
  const expected = generateVisualTokenCss()

  if (check) {
    const actual = await readFile(output, 'utf8').catch(() => undefined)
    if (actual !== expected) {
      throw new Error(
        `Generated visual tokens are stale: ${fileURLToPath(output)}. Run scripts/generate-visual-tokens.ts.`
      )
    }
    return
  }

  await writeFile(output, expected)
}

export const spec: CliSpec = {
  describe: 'Generate the CSS custom properties that mirror the view model\u2019s visual tokens.',
  flags: {
    check: { describe: 'Verify the generated file is current instead of writing it.', kind: 'boolean' },
    out: {
      describe: 'Generated CSS pathname. Defaults to the view model\u2019s tokens.',
      kind: 'string',
      value: 'path'
    }
  },
  run: 'self:tokens:generate',
  script: 'scripts/generate-visual-tokens.ts'
}

if (isDirectInvocation(import.meta.url)) {
  await runCli(spec, async (parsed) => {
    const out = parsed.string('out')
    const output = out ? pathToFileURL(resolve(out)) : generatedVisualTokensUrl
    const check = parsed.boolean('check')

    await generateVisualTokens({ check, output })
    const count = visualTokenEntries().length
    console.log(
      check
        ? `Visual tokens current: ${count} declarations in ${fileURLToPath(output)}`
        : `Visual tokens written: ${count} declarations to ${fileURLToPath(output)}`
    )
  })
}
